# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41838ef5d5d41be8f6d6f25e13ccdabbb6519f87dcbc4090cea07838563d069d114303be88f3e0ca9dcabd5ee8c2e0b5a715f10f55ae09cf83e67bd4c32bcc28

test:
  secret_key_base: 09acde843d777b1662daeebec919d3e8a7cac4c77718eda3395d48e38e81aa9c4efc01f97f97a485d4cb978f11cee8a20c6875ca54c0d938b196d14f6ebe3985

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
